apiVersion: v2
name: k8s-network-monitor
description: Kubernetes native network monitoring agent
type: application
version: 0.2.0
appVersion: "0.2.0"
icon: "https://raw.githubusercontent.com/pymisc/k8s-network-monitor/main/miscellaneous/k8s-network-monitor-icon.png"
