coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%

# Ignore only test code.
# Application code should always contribute to coverage metrics.
ignore:
  - "tests/**/*"